Nova verzija
sMirkovicc/v02 pull request #1
Opened 2024-07-04 12:26 UTC by sMirkovicc

dodat upis iz baze podataka u klasu pitanje

2024-07-04 12:39 UTC, RadeKornjaca requested changes
Nova verzija nije baš deskriptivno ime za ono što je urađeno. Komitove i Pull Request-ove treba nazivati koncizno, ali sa dovoljno informacija da se zna šta je urađeno.

2024-07-04 12:39 UTC, RadeKornjaca commented on main.cpp
> +        }
switch je ovde potpuno nepotreban. Sam IDKviza treba da ide u posebnu promenljivu. sql će se napraviti kao spoj stringova `SELECT * from pitanje where IDKviza=` i vrednosti te promenljive. Obrati pažnju da sql ne može u tom slučaju biti const char * !

P.S. Nije baš najpametnija opcija pravljenje SQL upita ručnim spajanjem stringova. Za ove stvari postoje prepared statements. Ne moraš ih sad ovde upotrebiti, ali ih svakako istraži, da vidiš na šta se misli.

https://xkcd.com/327/

2024-07-04 12:39 UTC, RadeKornjaca commented on main.cpp
> +        }
Isto tako, hardkodirana imena kvizova nisu dobar izbor, trebalo bi da pošalješ SELECT upit ka tabeli kviz prethodno, da se vidi kako se kviz zove.

2024-07-04 12:39 UTC, RadeKornjaca commented on main.cpp
> +        std::cout << "\t3. Muzika" << std::endl;
Umesto ovoga, poslati SELECT ka tabeli kviz koji dovlači nazive svih trenutno dostupnih kvizova. Provrteti kroz petlju i prikazati ih.

2024-07-04 12:39 UTC, RadeKornjaca commented on main.cpp
> +    std::vector<Pitanje> kolekcijaPitanja;
Sad bi možda mogla da razmisliš da umesto vektora pitanja imaš odmah objekat klase Kviz, jer bi u tom slučaju imala i ime izabranog kviza pored pitanja.

2024-07-04 12:39 UTC, RadeKornjaca commented on main.cpp
> +   //rc = sqlite3_open("kviz.db", &db);
Izbaci kod koji više ne koristiš.

2024-07-05 12:06 UTC, RadeKornjaca requested changes

2024-07-05 12:06 UTC, RadeKornjaca commented on main.cpp
> +    Kviz* ptrKviz = &kviz;
Ostavi samo ptrKviz ovde, a možeš alocirati novi kviz dinamički prilikom učitavanja.

2024-07-05 12:06 UTC, RadeKornjaca commented on main.cpp
> +        sql = "SELECT * from kviz where IDKviza=" + br_kviza;
Ovde negde kažeš samo ptrKviz = new Kviz. Ne zaboravi samo da ga obrišeš negde.

2024-07-05 12:17 UTC, RadeKornjaca requested changes

2024-07-05 12:17 UTC, RadeKornjaca commented on main.cpp
> +class Igra
E, sad tek vidim, što klasa igra nije u posebnom fajlu?

2024-07-05 12:19 UTC, sMirkovicc commented on main.cpp
> +class Igra
Zato što čekam da sigurno sve bude u redu prije nego što to uradim hahahah
Pošto sam dosta mijenjala koje metode postoje pa mi bilo nezgodno da na dva mjesta stalno pratim promjene

2024-07-05 12:25 UTC, RadeKornjaca commented on main.cpp
> +class Igra
Hajde, vreme je. :D

2024-07-08 08:58 UTC, RadeKornjaca approved these changes

2024-07-08 09:02 UTC, merged